# ----------------------------------------------------------------------
# ADMINISTRATIVE BOUNDARY INDEXING
# ----------------------------------------------------------------------
target_area = {
    "Africa": [
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Canary Islands",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comores",
        "Congo Brazzaville",
        "Congo Democratic Republic",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Ethiopia",
        "Gabon",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Ivory Coast",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Saint Helena, Ascension, and Tristan da Cunha",
        "Sao Tome and Principe",
        "Senegal and Gambia",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "Swaziland",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
    ],
    "Antarctica": [],
    "Asia": [
        "Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bangladesh",
        "Bhutan",
        "Cambodia",
        "China",
        "East Timor",
        "GCS States",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel and Palestine",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Krygyzstan",
        "Laos",
        "Lebanon",
        "Malaysia, Singapore, and Brunei",
        "Maldives",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "North Korea",
        "Pakistan",
        "Philippines",
        "Russian Federation",
        "South Korea",
        "Sri Lanka",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Turkmenistan",
        "Uzbekistan",
        "Vietnam",
        "Yemen",
    ],
    "Australia Oceania": [
        "American Oceania",
        "Australia",
        "Cook Islands",
        "Fiji",
        "Ile de Clipperton",
        "Kirbati",
        "Marshall Islands",
        "Micronesia",
        "Nauru",
        "New Caledonia",
        "New Zealand",
        "Niue",
        "Palau",
        "Papua New Guinea",
        "Pitcairn Islands",
        "Polynesie Francaise",
        "Samoa",
        "Solomon Islands",
        "Tokelau",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
        "Wallis et Futuna",
    ],
    "Central America": [
        "Bahamas",
        "Belize",
        "Costa Rica",
        "El Salvador",
        "Guatemala",
        "Haiti and Dominican Republic",
        "Honduras",
        "Jamaica",
        "Nicaragua",
        "Panama",
    ],
    "Europe": [],
    "North America": ["Canada", "Greenland", "Mexico", "United States of America"],
    "South America": [
        "Argentina",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela",
    ],
}

PROVINCES = {
    "Canada": [
        "Alberta",
        "British Columbia",
        "Manitoba",
        "New Brunswick",
        "Newfoundland and Labrador",
        "Nova Scotia",
        "Ontario",
        "Prince Edward Island",
        "Quebec",
        "Saskatchewan",
    ],
}

# Note: everything is in English (no cote d'ivoire -> ivory coast)
# Exceptions:
# africa -> congo (republic/brazzaville) -> congo-brazzaville
# africa -> congo (democratic republic/kinshasa) -> congo-democratic-republic
# africa -> saint helena, ascension and tristan da cunha -> saint-helena-ascension-and-tristan-da-cunha
# africa -> sao tome and principe -> sao-tome-and-principe
# africa -> senegal-and-gambia -> senegal-and-gambia
# asia -> israel and palestine -> israel-palestine
# asia -> russian federation -> russia
# asia -> malaysia, singapore and brunei -> malaysia-singapore-brunei
# australia and oceania -> australia-oceania
# central america -> haiti and dominican republic -> haiti-and-domrep
# europe -> guernsey and jersey -> guernsey-jersey
# europe -> ireland and northern ireland -> ireland-and-northern-ireland
# north america -> united states -> us


# hardcoding list of countries later
